### ISSUE TITLE
Another potential PHP compatibility issue

### ISSUE THREAD

**Issue by iMattPro** [s9e/SweetDOM#4]
I came across this when using phpBB's QuickInstall tool to install a build of phpBB 4 with forum/user data, where a bunch of posts are randomly generated by the tool. 

The issue seems to be with SweetDOM, which is somehow involved during phpBB's message parsing. The SweetDOM version used in this build was 3.2.0. The PHP environment was 8.2.0.

```
HP Fatal error:  Uncaught DOMException: Not Found Error in /phpBB4/vendor/s9e/sweetdom/src/NodeTraits/MagicMethods.php:44
Stack trace:
#0 /phpBB4/vendor/s9e/sweetdom/src/NodeTraits/MagicMethods.php(44): DOMElement->replaceWith(Object(s9e\SweetDOM\Element))
#1 /phpBB4/vendor/s9e/sweetdom/src/NodeTraits/PolyfillMethods.php(35): s9e\SweetDOM\Element->magicMethodsCall('replaceWithXslC...', Array)
#2 /phpBB4/vendor/s9e/sweetdom/src/NodeTraits/DeprecatedMethods.php(48): s9e\SweetDOM\Element->polyfillMethodsCall('replaceWithXslC...', Array)
#3 /phpBB4/vendor/s9e/text-formatter/src/Configurator/TemplateNormalizations/DeoptimizeIf.php(27): s9e\SweetDOM\Element->__call('replaceWithXslC...', Array)
#4 /phpBB4/vendor/s9e/text-formatter/src/Configurator/TemplateNormalizations/AbstractNormalization.php(119): s9e\TextFormatter\Configurator\TemplateNormalizations\DeoptimizeIf->normalizeElement(Object(s9e\SweetDOM\Element))
#5 /phpBB4/vendor/s9e/text-formatter/src/Configurator/TemplateNormalizations/AbstractNormalization.php(48): s9e\TextFormatter\Configurator\TemplateNormalizations\AbstractNormalization->normalizeNode(Object(s9e\SweetDOM\Element))
#6 /phpBB4/vendor/s9e/text-formatter/src/Configurator/TemplateNormalizer.php(146): s9e\TextFormatter\Configurator\TemplateNormalizations\AbstractNormalization->normalize(Object(s9e\SweetDOM\Element))
#7 /phpBB4/phpbb/textformatter/s9e/factory.php(552): s9e\TextFormatter\Configurator\TemplateNormalizer->normalizeTemplate('<blockquote><xs...')
#8 /phpBB4/phpbb/textformatter/s9e/factory.php(286): phpbb\textformatter\s9e\factory->get_default_bbcodes(Object(s9e\TextFormatter\Configurator))
#9 /phpBB4/phpbb/textformatter/s9e/factory.php(394): phpbb\textformatter\s9e\factory->get_configurator()
#10 /phpBB4/phpbb/textformatter/s9e/parser.php(48): phpbb\textformatter\s9e\factory->regenerate()
#11 [internal function]: phpbb\textformatter\s9e\parser->__construct(Object(phpbb\cache\driver\file), '_text_formatter...', Object(phpbb\textformatter\s9e\factory), Object(phpbb\event\dispatcher))
#12 /phpBB4/vendor/symfony/dependency-injection/ContainerBuilder.php(1140): ReflectionClass->newInstanceArgs(Array)
#13 /phpBB4/vendor/symfony/dependency-injection/ContainerBuilder.php(586): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, true, 'text_formatter....')
#14 /phpBB4/vendor/symfony/dependency-injection/ContainerBuilder.php(564): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('text_formatter....', 1, Array, true)
#15 /phpBB4/vendor/symfony/dependency-injection/ContainerBuilder.php(531): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('text_formatter....', 1)
#16 /boards/t4/includes/message_parser.php(1169): Symfony\Component\DependencyInjection\ContainerBuilder->get('text_formatter....')
#17 /boards/t4/includes/functions_content.php(723): parse_message->parse(false, false, false, true, true, true, true, 'post')
#18 /includes/qi_populate.php(584): generate_text_for_storage('Test forum 1', '', '', 0, false, false, false)
#19 /includes/qi_populate.php(514): qi_populate->_create_forums(0, 1, Object(acp_forums))
#20 /includes/qi_populate.php(167): qi_populate->create_forums()
#21 /modules/qi_create.php(853): qi_populate->run()
#22 /includes/qi_module.php(45): qi_create->run()
#23 /index.php(256): qi_module->load(Object(qi_create), 'qi_main')
#24 {main} thrown in /phpBB4/vendor/s9e/sweetdom/src/NodeTraits/MagicMethods.php on line 44
```

**Comment by JoshyPHP** [comment]
Upgrade to 3.3.0 which contains a number of workarounds for some bugs found in older versions of PHP 8.1 and 8.2, that should fix it.

https://github.com/s9e/SweetDOM/releases/tag/3.3.0

**Comment by iMattPro** [comment]
That does fix it. Thanks!
